#!/usr/bin/python3
import sys

my_file = sys.argv[1]
m = 0
n = 0
with open(my_file, 'r') as fl:
    for line in fl.readlines():
        a = int(line)
        for i in range(2, int(a / 2)):
            if a % i == 0:
                m = int(a / i)
                n = i
                break
        print("{:d}={:d}*{:d}".format(a, m, n))
